export const types = {
    SET_BANNER: "booking/SET_BANNER",
    GET_MOVIES_PAGES: "booking/GET_MOVIES_PAGES",
    SENDING_TRAILER_URL: "booking/SENDING_TRAILER_URL",
    GET_MOVIES_LIST: "booking/GET_MOVIES_LIST",
    GET_DATA_OF_SHOW_ID: "booking/GET_DATA_OF_SHOW_ID",
    START_SELECT_SEATS: "booking/START_SELECT_SEATS",
    SELECTING_SEATS: "booking/SELECTING_SEATS",
    GETBACK_STEP_0 : "booking/GETBACK_STEP_0",
    SET_BOOKING_STEP:"booking/SET_BOOKING_STEP"
}