export const adminTypes = {
    FETCH_MOVIE_DETAIL : 'admin/FETCH_MOVIE_DETAIL',
    FETCH_USER_PAGINATION: 'admin/FETCH_USER',
    DELETE_FILM: 'admin/DELETE_FILM',
    UPDATE_DETAIL_FILM: 'admin/UPDATE_DETAIL_FILM',
    GET_DETAIL_FILM: 'admin/GET_DETAIL_FILM ',
}

