export const adminTypes = {
    FETCH_MOVIE_DETAIL : 'admin/FETCH_MOVIE_DETAIL',
    FETCH_USER_PAGINATION: 'admin/FETCH_USER',
    DELETE_FILM: 'admin/DELETE_FILM',
    UPDATE_DETAIL_FILM: 'admin/UPDATE_DETAIL_FILM',
    GET_DETAIL_FILM: 'admin/GET_DETAIL_FILM ',
}

export const adminToken = {
    adminToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWJjMTIzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiZWdnZzEyMzc5QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJRdWFuVHJpIiwiZWdnZzEyMzc5QGdtYWlsLmNvbSIsIkdQMDEiXSwibmJmIjoxNjc3OTAzMzI1LCJleHAiOjE2Nzc5MDY5MjV9.wPI54J_fcl7qv47vvet1diH48wOJudd6YU7AVr6A9XY"
}